In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import numpy
import sys
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [3]:
df = pd.read_csv('/home/fjordan/Documentos/Proyectos/Personales/proyectos-Python/Analisis Lamine-Pedri/data/clean/players_2025.csv')
df

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK,Per 90 Minutes_xG,Per 90 Minutes_xAG,Per 90 Minutes_xG+xAG,Per 90 Minutes_npxG,Per 90 Minutes_npxG+xAG
0,Brenden Aaronson,us USA,"FW,MF",Leeds United,eng Premier League,25-089,2000.0,21,15,1334,...,0.27,0.20,0.47,0.27,0.47,0.21,0.20,0.41,0.21,0.41
1,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19-251,2006.0,1,0,45,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20-007,2006.0,11,1,288,...,0.62,0.00,0.62,0.62,0.62,0.70,0.02,0.73,0.70,0.73
3,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26-063,1999.0,13,11,943,...,0.19,0.00,0.19,0.00,0.00,0.19,0.04,0.23,0.04,0.08
4,Ali Abdi,tn TUN,"DF,MF",Nice,fr Ligue 1,32-030,1993.0,10,6,485,...,0.00,0.00,0.00,0.00,0.00,0.00,0.09,0.09,0.00,0.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,Yanis Zouaoui,dz ALG,DF,Le Havre,fr Ligue 1,31-193,1994.0,17,16,1412,...,0.00,0.06,0.06,0.00,0.06,0.04,0.11,0.14,0.04,0.14
2474,Igor Zubeldia,es ESP,DF,Real Sociedad,es La Liga,28-295,1997.0,15,15,1350,...,0.00,0.07,0.07,0.00,0.07,0.01,0.05,0.06,0.01,0.06
2475,Martín Zubimendi,es ESP,MF,Arsenal,eng Premier League,26-351,1999.0,22,21,1847,...,0.15,0.05,0.19,0.15,0.19,0.10,0.05,0.15,0.10,0.15
2476,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,27-033,1998.0,16,12,930,...,0.10,0.29,0.39,0.10,0.39,0.09,0.25,0.33,0.09,0.33
2477,Milan Đurić,ba BIH,FW,Parma,it Serie A,35-242,1990.0,12,0,74,...,0.00,0.00,0.00,0.00,0.00,0.28,0.00,0.28,0.28,0.28

In [4]:
df = df[df['Playing Time_Min']>=300]
df

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK,Per 90 Minutes_xG,Per 90 Minutes_xAG,Per 90 Minutes_xG+xAG,Per 90 Minutes_npxG,Per 90 Minutes_npxG+xAG
0,Brenden Aaronson,us USA,"FW,MF",Leeds United,eng Premier League,25-089,2000.0,21,15,1334,...,0.27,0.20,0.47,0.27,0.47,0.21,0.20,0.41,0.21,0.41
3,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26-063,1999.0,13,11,943,...,0.19,0.00,0.19,0.00,0.00,0.19,0.04,0.23,0.04,0.08
4,Ali Abdi,tn TUN,"DF,MF",Nice,fr Ligue 1,32-030,1993.0,10,6,485,...,0.00,0.00,0.00,0.00,0.00,0.00,0.09,0.09,0.00,0.09
5,Salis Abdul Samed,gh GHA,MF,Nice,fr Ligue 1,25-299,2000.0,12,7,528,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,Saud Abdulhamid,sa KSA,DF,Lens,fr Ligue 1,26-185,1999.0,12,3,371,...,0.00,0.24,0.24,0.00,0.24,0.05,0.17,0.22,0.05,0.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2472,Nadir Zortea,it ITA,DF,Bologna,it Serie A,26-214,1999.0,16,10,1025,...,0.00,0.09,0.09,0.00,0.09,0.03,0.16,0.19,0.03,0.19
2473,Yanis Zouaoui,dz ALG,DF,Le Havre,fr Ligue 1,31-193,1994.0,17,16,1412,...,0.00,0.06,0.06,0.00,0.06,0.04,0.11,0.14,0.04,0.14
2474,Igor Zubeldia,es ESP,DF,Real Sociedad,es La Liga,28-295,1997.0,15,15,1350,...,0.00,0.07,0.07,0.00,0.07,0.01,0.05,0.06,0.01,0.06
2475,Martín Zubimendi,es ESP,MF,Arsenal,eng Premier League,26-351,1999.0,22,21,1847,...,0.15,0.05,0.19,0.15,0.19,0.10,0.05,0.15,0.10,0.15
2476,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,27-033,1998.0,16,12,930,...,0.10,0.29,0.39,0.10,0.39,0.09,0.25,0.33,0.09,0.33

In [5]:
df.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born',
       'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min',
       'Playing Time_90s', 'Performance_Gls', 'Performance_Ast',
       'Performance_G+A', 'Performance_G-PK', 'Performance_PK',
       'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR',
       'Expected_xG', 'Expected_npxG', 'Expected_xAG', 'Expected_npxG+xAG',
       'Progression_PrgC', 'Progression_PrgP', 'Progression_PrgR',
       'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A',
       'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK', 'Per 90 Minutes_xG',
       'Per 90 Minutes_xAG', 'Per 90 Minutes_xG+xAG', 'Per 90 Minutes_npxG',
       'Per 90 Minutes_npxG+xAG'],
      dtype='object')

In [6]:
def explore_cluster(df, n_cluster, cols, pos=None, scale=True):

    df = df.copy()

    # 1. Filtrado por posición (si aplica)
    if pos is not None:
        df = df[df["Pos"].str.contains(pos)]

    df = df.reset_index(drop=True)

    # 2. Selección de features
    X = df[cols]

    # 3. Normalización (CLAVE)
    if scale:
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
    else:
        X_scaled = X.values

    # 4. Clustering
    cluster = KMeans(n_clusters=n_cluster, random_state=1)
    labels = cluster.fit_predict(X_scaled)

    df["cluster"] = labels.astype(str)

    # 5. Promedios por cluster (en escala ORIGINAL, no normalizada)
    df_group = df.groupby("cluster")[cols].mean()

    # 6. Visualizaciones exploratorias
    sns.set_theme()

    if len(cols) == 1:
        plt.figure(figsize=(12, 8))
        sns.boxplot(data=df, x="cluster", y=cols[0])
        plt.show()

    elif len(cols) == 2:
        plt.figure(figsize=(12, 8))
        sns.scatterplot(data=df, x=cols[0], y=cols[1], hue="cluster")
        plt.show()

    elif len(cols) == 3:
        fig = px.scatter_3d(
            df,
            x=cols[0],
            y=cols[1],
            z=cols[2],
            color="cluster"
        )
        fig.show()

    return df_group, df

In [7]:
columnas = ['Per 90 Minutes_xAG','Per 90 Minutes_xG', 'Per 90 Minutes_xG+xAG','Progression_PrgP','Progression_PrgC','Progression_PrgR']

In [8]:
df_group, df_final =  explore_cluster(df,4,columnas, 'MF')

In [9]:
df_cluster = df_final.copy()

In [10]:
df_cluster_pedri = df_cluster[df_cluster['cluster']=='2']
df_cluster_pedri = df_cluster_pedri.reset_index(drop=True)

Qué está pasando aquí
StandardScaler se utiliza para construir espacios de similitud, donde las distancias entre jugadores son significativas.

Tienes variables con escalas distintas:

xG ≈ 0.1 – 0.5

xAG ≈ 0.05 – 0.4

PrgP ≈ 5 – 80

PrgR ≈ 10 – 120

Si no haces nada:

PrgP y PrgR dominan la distancia

xG y xAG casi no pesan

👉 Eso sería incorrecto futbolísticamente.

Qué hace StandardScaler

Convierte cada variable en:

z=
σ
x−μ
	​


Resultado:

media = 0

desviación estándar = 1

todas las variables pesan igual

📌 Esto es solo para que la matemática de la distancia funcione bien.

In [11]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_cluster_pedri[columnas])

Aquí pasa esto:

X_scaled es una matriz numérica

no tiene nombres de jugadores

pero mantiene el orden de filas

Tú usas el índice original para decir:

“dame la fila estandarizada que corresponde a Pedri”

El reshape(1, -1) solo dice:

“trátalo como una fila, no como una lista”

Nada más.

In [12]:
idx_pedri = df_cluster_pedri[df_cluster_pedri["Player"] == "Pedri"].index[0]
pedri_vector = X_scaled[idx_pedri].reshape(1, -1)

Esto produce:

un número por jugador

cuanto más pequeño, más parecido a Pedri

ya incorpora TODAS las variables correctamente balanceadas

📌 Aquí se acaba la matemática futbolística.
No se vuelve a tocar.

In [13]:
distances = euclidean_distances(X_scaled, pedri_vector).flatten()
df_cluster_pedri["distance_to_pedri"] = distances

In [14]:
df_replacements = df_cluster_pedri[
    df_cluster_pedri["Player"] != "Pedri"
].copy()

Si usaras StandardScaler aquí:

obtendrías valores negativos

valores > 1

sin interpretación clara

Pero tú quieres:

combinar métricas

sumar pesos

crear un score final

👉 Para eso necesitas una escala común y comprensible: 0–1.

Eso es exactamente lo que hace MinMaxScaler.

MinMaxScaler se utiliza para construir rankings, donde las variables deben ser comparables y ponderables en una misma escala.

In [15]:
scaler = MinMaxScaler()

df_replacements["distance_norm"] = scaler.fit_transform(
    df_replacements[["distance_to_pedri"]]
)

df_replacements["minutes_penalty"] = np.log1p(
    df_replacements["Playing Time_Min"]
)
"""Esto responde a otra idea distinta:

no quieres que 3000 minutos penalicen 10 veces más que 300

quieres una penalización no lineal

reflejar “estatus” más que volumen puro"""

df_replacements["minutes_penalty_norm"] = MinMaxScaler().fit_transform(
    df_replacements[["minutes_penalty"]]
)
"""Esto responde a otra idea distinta:

no quieres que 3000 minutos penalicen 10 veces más que 300

quieres una penalización no lineal

reflejar “estatus” más que volumen puro"""

df_replacements["replacement_score"] = (
    0.6 * df_replacements["distance_norm"] +
    0.4 * df_replacements["minutes_penalty_norm"]
)
"""Estás diciendo claramente:

“Prefiero equivocarme por exceso de similitud antes que por exceso de viabilidad”."""

'Estás diciendo claramente:\n\n“Prefiero equivocarme por exceso de similitud antes que por exceso de viabilidad”.'

In [16]:
df_replacements = df_replacements.sort_values("replacement_score")

In [17]:
df_replacements

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Per 90 Minutes_xAG,Per 90 Minutes_xG+xAG,Per 90 Minutes_npxG,Per 90 Minutes_npxG+xAG,cluster,distance_to_pedri,distance_norm,minutes_penalty,minutes_penalty_norm,replacement_score
98,Maxime Lopez,fr FRA,MF,Paris FC,fr Ligue 1,28-046,1997.0,16,16,1440,...,0.27,0.29,0.02,0.29,2,1.520612,0.008277,7.273093,0.780730,0.317258
141,Declan Rice,eng ENG,MF,Arsenal,eng Premier League,27-005,1999.0,21,20,1786,...,0.18,0.32,0.13,0.32,2,1.475274,0.000000,7.488294,0.928994,0.371598
189,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,27-033,1998.0,16,12,930,...,0.25,0.33,0.09,0.33,2,3.229358,0.320219,6.836259,0.479771,0.384040
131,Azzedine Ounahi,ma MAR,"MF,FW",Girona,es La Liga,25-275,2000.0,10,9,780,...,0.16,0.27,0.11,0.27,2,3.739888,0.413420,6.660575,0.358733,0.391545
148,Lazar Samardzic,rs SRB,MF,Atalanta,it Serie A,23-329,2002.0,16,5,581,...,0.20,0.41,0.21,0.41,2,4.516961,0.555279,6.366470,0.156108,0.395611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,José Luis García Vayá,es ESP,MF,Valencia,es La Liga,27-161,1998.0,18,16,1415,...,0.07,0.23,0.06,0.13,2,6.480265,0.913693,7.255591,0.768672,0.855685
2,Michel Aebischer,ch SUI,MF,Pisa,it Serie A,29-013,1997.0,20,19,1673,...,0.05,0.06,0.01,0.06,2,6.238508,0.869559,7.422971,0.883990,0.875331
78,Mikel Jauregizar,es ESP,MF,Athletic Club,es La Liga,22-067,2003.0,20,20,1735,...,0.05,0.11,0.06,0.11,2,6.284798,0.878009,7.459339,0.909045,0.890424
20,Antonio Blanco,es ESP,MF,Alavés,es La Liga,25-180,2000.0,18,18,1555,...,0.04,0.07,0.03,0.07,2,6.953034,1.000000,7.349874,0.833629,0.933451
107,Nemanja Matić,rs SRB,MF,Sassuolo,it Serie A,37-171,1988.0,20,20,1773,...,0.03,0.04,0.01,0.04,2,6.764487,0.965580,7.480992,0.923964,0.948933

In [18]:
df_replacements.to_csv(
    "/home/fjordan/Documentos/Proyectos/Personales/proyectos-Python/Analisis Lamine-Pedri/data/clean/replacements_tableau.csv",
    index=False,
    sep=";",              # separador europeo
    encoding="utf-8-sig"  # acentos y nombres correctos
)

In [19]:
df_replacements.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Comp', 'Age', 'Born',
       'Playing Time_MP', 'Playing Time_Starts', 'Playing Time_Min',
       'Playing Time_90s', 'Performance_Gls', 'Performance_Ast',
       'Performance_G+A', 'Performance_G-PK', 'Performance_PK',
       'Performance_PKatt', 'Performance_CrdY', 'Performance_CrdR',
       'Expected_xG', 'Expected_npxG', 'Expected_xAG', 'Expected_npxG+xAG',
       'Progression_PrgC', 'Progression_PrgP', 'Progression_PrgR',
       'Per 90 Minutes_Gls', 'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A',
       'Per 90 Minutes_G-PK', 'Per 90 Minutes_G+A-PK', 'Per 90 Minutes_xG',
       'Per 90 Minutes_xAG', 'Per 90 Minutes_xG+xAG', 'Per 90 Minutes_npxG',
       'Per 90 Minutes_npxG+xAG', 'cluster', 'distance_to_pedri',
       'distance_norm', 'minutes_penalty', 'minutes_penalty_norm',
       'replacement_score'],
      dtype='object')

In [20]:
df_replacements[
    ["Player", "Playing Time_Min", "distance_to_pedri", "replacement_score"]
].head(10)

,Player,Playing Time_Min,distance_to_pedri,replacement_score
98,Maxime Lopez,1440,1.520612,0.317258
141,Declan Rice,1786,1.475274,0.371598
189,Martin Ødegaard,930,3.229358,0.384040
131,Azzedine Ounahi,780,3.739888,0.391545
148,Lazar Samardzic,581,4.516961,0.395611
85,Bilal El Khannouss,948,3.337512,0.401164
46,Edu Expósito,1327,2.609397,0.414012
147,Osame Sahraoui,463,5.256321,0.414153
53,Chris Führich,654,4.390908,0.414368
91,Noa Lang,666,4.654600,0.448254

In [21]:
df_group_FW, df_final_FW =  explore_cluster(df,4,columnas, 'FW')

In [22]:
df_cluster_FW = df_final_FW.copy()

In [23]:
df_group_FW

,Per 90 Minutes_xAG,Per 90 Minutes_xG,Per 90 Minutes_xG+xAG,Progression_PrgP,Progression_PrgC,Progression_PrgR
cluster,,,,,,
0,0.088672,0.199805,0.288711,16.386719,11.988281,38.675781
1,0.182517,0.185850,0.368367,37.476190,31.829932,70.952381
2,0.158065,0.528468,0.686613,16.750000,13.354839,50.588710
3,0.254655,0.297759,0.551379,57.206897,59.568966,129.655172

In [24]:
df_cluster_lamine = df_cluster_FW[df_cluster_FW['cluster']=='3']
df_cluster_lamine = df_cluster_lamine.reset_index(drop=True)

In [25]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_cluster_lamine[columnas])

In [26]:
idx_lamine = df_cluster_lamine[df_cluster_lamine["Player"] == "Lamine Yamal"].index[0]
lamine_vector = X_scaled[idx_lamine].reshape(1, -1)

In [27]:
distances = euclidean_distances(X_scaled, lamine_vector).flatten()
df_cluster_lamine["distance_to_lamine"] = distances

In [28]:
df_replacements = df_cluster_lamine[
    df_cluster_lamine["Player"] != "Lamine Yamal"
].copy()

In [29]:
scaler = MinMaxScaler()

df_replacements["distance_norm"] = scaler.fit_transform(
    df_replacements[["distance_to_lamine"]]
)

df_replacements["minutes_penalty"] = np.log1p(
    df_replacements["Playing Time_Min"]
)

df_replacements["minutes_penalty_norm"] = MinMaxScaler().fit_transform(
    df_replacements[["minutes_penalty"]]
)

df_replacements["replacement_score"] = (
    0.99 * df_replacements["distance_norm"] +
    0.01 * df_replacements["minutes_penalty_norm"]
)

In [30]:
df_replacements = df_replacements.sort_values("replacement_score")

In [31]:
df_replacements.loc[
    (df_replacements['Playing Time_Min'] >= 400) &
    (df_replacements['Playing Time_Min'] <= 1200),
    ["Player", "Playing Time_Min", "distance_to_lamine", "replacement_score"]
].head(50)

,Player,Playing Time_Min,distance_to_lamine,replacement_score
13,Jeremy Doku,1168,2.457045,0.251082
54,Nico Williams,1128,2.792286,0.343321
43,Mohamed Salah,1183,3.250759,0.470445
37,Nicolas Pépé,1052,3.275530,0.476080
40,Jesus Rodríguez,1082,3.305188,0.484561
15,Matias Fernandez-Pardo,954,3.344344,0.494081
39,Marcus Rashford,1138,3.348745,0.497111
17,Alejandro Garnacho,817,3.717223,0.595480
20,Anthony Gordon,1064,3.817097,0.625782
3,Bradley Barcola,834,3.887563,0.642741
27,Takefusa Kubo,1179,3.943149,0.661655
4,Ander Barrenetxea,1052,3.979100,0.670412
29,Khvicha Kvaratskhelia,749,3.992848,0.670716
7,Rayan Cherki,885,4.010533,0.677317
53,Carlos Vicente,1176,4.157824,0.720924
52,Leandro Trossard,1176,4.171776,0.724778
8,Félix Correia,1071,4.197717,0.730981
14,Abde Ezzalzouli,780,4.253319,0.743078
33,Jacob Murphy,1010,4.253886,0.745892
51,Bazoumana Touré,1110,4.362155,0.776768
47,Moses Simon,1146,4.542499,0.826909

In [32]:
df_replacements[
    ["Player", "Playing Time_Min", "distance_to_lamine", "replacement_score"]
].head(50)

,Player,Playing Time_Min,distance_to_lamine,replacement_score
57,Kenan Yıldız,1661,1.564561,0.008192
13,Jeremy Doku,1168,2.457045,0.251082
10,Charles De Ketelaere,1409,2.690434,0.317476
54,Nico Williams,1128,2.792286,0.343321
42,Bukayo Saka,1456,2.888168,0.372430
34,Pedro Neto,1729,2.911810,0.380728
16,Cody Gakpo,1422,2.919990,0.380976
2,Antony,1261,2.934520,0.383753
21,Jack Grealish,1627,3.100912,0.432334
22,Mason Greenwood,1355,3.125817,0.437331
25,Vinicius Júnior,1491,3.163472,0.448716
43,Mohamed Salah,1183,3.250759,0.470445
37,Nicolas Pépé,1052,3.275530,0.476080
40,Jesus Rodríguez,1082,3.305188,0.484561
15,Matias Fernandez-Pardo,954,3.344344,0.494081
39,Marcus Rashford,1138,3.348745,0.497111
12,Luis Díaz,1432,3.416023,0.518057
31,Yankuba Minteh,1541,3.561440,0.558978
45,Antoine Semenyo,1798,3.568788,0.562594
17,Alejandro Garnacho,817,3.717223,0.595480
20,Anthony Gordon,1064,3.817097,0.625782
44,Romano Schmid,1484,3.837648,0.634881
26,Ilan Kebbal,1490,3.838526,0.635165
3,Bradley Barcola,834,3.887563,0.642741
1,Julián Álvarez,1433,3.930764,0.660241
27,Takefusa Kubo,1179,3.943149,0.661655
35,Michael Olise,1370,3.957919,0.667279
4,Ander Barrenetxea,1052,3.979100,0.670412
29,Khvicha Kvaratskhelia,749,3.992848,0.670716
7,Rayan Cherki,885,4.010533,0.677317
11,Romain Del Castillo,1369,4.002292,0.679528
53,Carlos Vicente,1176,4.157824,0.720924
46,Giuliano Simeone,1421,4.158569,0.723077
23,Callum Hudson-Odoi,1210,4.169409,0.724417
52,Leandro Trossard,1176,4.171776,0.724778
8,Félix Correia,1071,4.197717,0.730981
14,Abde Ezzalzouli,780,4.253319,0.743078
38,Matteo Politano,1311,4.234238,0.743148
5,Álex Berenguer,1286,4.240137,0.744579
33,Jacob Murphy,1010,4.253886,0.745892
48,Matìas Soulé,1385,4.256026,0.749731
0,Maghnes Akliouche,1385,4.317693,0.766764
32,Diego Moreira,1307,4.333442,0.770518
6,Jarrod Bowen,1980,4.322008,0.771633
24,João Pedro,1598,4.337429,0.773687
51,Bazoumana Touré,1110,4.362155,0.776768
9,Cucho,1645,4.359687,0.780133
41,Morgan Rogers,1957,4.370136,0.784807
49,Issa Soumaré,1553,4.401575,0.791111
18,Yann Gboho,1440,4.410706,0.792856

codigo necesario para utilizar en Tableau

In [42]:
# Crear dataset final completo
df_final = df_cluster_lamine.copy()

# Añadir flag de target
df_final["is_target"] = df_final["Player"].eq("Lamine Yamal")

# Añadir replacement_score solo para los otros jugadores
df_final = df_final.merge(
    df_replacements[["Player", "replacement_score"]],
    on="Player",
    how="left"
)

In [43]:
df_final["is_replacement_candidate"] = df_final["replacement_score"].notna()

In [44]:
df_final = df_final.sort_values("replacement_score")
df_final["replacement_rank"] = range(1, len(df_final)+1)

In [45]:
df_final.loc[df_final["is_target"] == True, "replacement_rank"] = None

In [52]:
df_final

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,Playing Time_Min,...,Per 90 Minutes_xAG,Per 90 Minutes_xG+xAG,Per 90 Minutes_npxG,Per 90 Minutes_npxG+xAG,cluster,distance_to_lamine,is_target,replacement_score,is_replacement_candidate,replacement_rank
57,Kenan Yıldız,tr TUR,"MF,FW",Juventus,it Serie A,20-260,2005.0,20,19,1661,...,0.25,0.60,0.25,0.50,3,1.564561,False,0.008192,True,1.0
13,Jeremy Doku,be BEL,"MF,FW",Manchester City,eng Premier League,23-237,2002.0,19,13,1168,...,0.53,0.67,0.14,0.67,3,2.457045,False,0.251082,True,2.0
10,Charles De Ketelaere,be BEL,"MF,FW",Atalanta,it Serie A,24-315,2001.0,19,16,1409,...,0.34,0.51,0.18,0.51,3,2.690434,False,0.317476,True,3.0
54,Nico Williams,es ESP,FW,Athletic Club,es La Liga,23-191,2002.0,16,13,1128,...,0.30,0.65,0.22,0.52,3,2.792286,False,0.343321,True,4.0
42,Bukayo Saka,eng ENG,FW,Arsenal,eng Premier League,24-136,2001.0,20,16,1456,...,0.31,0.65,0.29,0.60,3,2.888168,False,0.372430,True,5.0
34,Pedro Neto,pt POR,FW,Chelsea,eng Premier League,25-316,2000.0,22,20,1729,...,0.22,0.42,0.20,0.42,3,2.911810,False,0.380728,True,6.0
16,Cody Gakpo,nl NED,FW,Liverpool,eng Premier League,26-257,1999.0,20,16,1422,...,0.25,0.57,0.32,0.57,3,2.919990,False,0.380976,True,7.0
2,Antony,br BRA,FW,Real Betis,es La Liga,25-329,2000.0,15,15,1261,...,0.18,0.50,0.32,0.50,3,2.934520,False,0.383753,True,8.0
21,Jack Grealish,eng ENG,FW,Everton,eng Premier League,30-131,1995.0,20,18,1627,...,0.24,0.36,0.12,0.36,3,3.100912,False,0.432334,True,9.0
22,Mason Greenwood,eng ENG,"FW,MF",Marseille,fr Ligue 1,24-110,2001.0,17,16,1355,...,0.28,0.88,0.33,0.61,3,3.125817,False,0.437331,True,10.0
25,Vinicius Júnior,br BRA,"FW,MF",Real Madrid,es La Liga,25-191,2000.0,20,17,1491,...,0.22,0.63,0.31,0.53,3,3.163472,False,0.448716,True,11.0
43,Mohamed Salah,eg EGY,"FW,MF",Liverpool,eng Premier League,33-218,1992.0,14,12,1183,...,0.22,0.57,0.29,0.51,3,3.250759,False,0.470445,True,12.0
37,Nicolas Pépé,ci CIV,"FW,MF",Villarreal,es La Liga,30-235,1995.0,18,11,1052,...,0.25,0.69,0.44,0.69,3,3.275530,False,0.476080,True,13.0
40,Jesus Rodríguez,es ESP,FW,Como,it Serie A,20-059,2005.0,17,11,1082,...,0.32,0.50,0.18,0.50,3,3.305188,False,0.484561,True,14.0
15,Matias Fernandez-Pardo,be BEL,FW,Lille,fr Ligue 1,20-350,2005.0,13,11,954,...,0.25,0.51,0.26,0.51,3,3.344344,False,0.494081,True,15.0
39,Marcus Rashford,eng ENG,FW,Barcelona,es La Liga,28-080,1997.0,19,12,1138,...,0.26,0.59,0.32,0.59,3,3.348745,False,0.497111,True,16.0
12,Luis Díaz,co COL,FW,Bayern Munich,de Bundesliga,29-006,1997.0,17,16,1432,...,0.24,0.85,0.61,0.85,3,3.416023,False,0.518057,True,17.0
31,Yankuba Minteh,gm GAM,FW,Brighton,eng Premier League,21-181,2004.0,19,18,1541,...,0.26,0.42,0.16,0.42,3,3.561440,False,0.558978,True,18.0
45,Antoine Semenyo,gh GHA,"FW,MF",Bournemouth,eng Premier League,26-012,2000.0,20,20,1798,...,0.11,0.44,0.26,0.36,3,3.568788,False,0.562594,True,19.0
17,Alejandro Garnacho,ar ARG,FW,Chelsea,eng Premier League,21-202,2004.0,14,11,817,...,0.36,0.59,0.23,0.59,3,3.717223,False,0.595480,True,20.0
20,Anthony Gordon,eng ENG,FW,Newcastle United,eng Premier League,24-329,2001.0,17,15,1064,...,0.25,0.64,0.25,0.50,3,3.817097,False,0.625782,True,21.0
44,Romano Schmid,at AUT,"MF,FW",Werder Bremen,de Bundesliga,25-357,2000.0,17,17,1484,...,0.35,0.61,0.10,0.45,3,3.837648,False,0.634881,True,22.0
26,Ilan Kebbal,dz ALG,"FW,MF",Paris FC,fr Ligue 1,27-194,1998.0,17,17,1490,...,0.19,0.46,0.17,0.36,3,3.838526,False,0.635165,True,23.0
3,Bradley Barcola,fr FRA,FW,Paris Saint-Germain,fr Ligue 1,23-139,2002.0,15,9,834,...,0.22,0.65,0.44,0.65,3,3.887563,False,0.642741,True,24.0
1,Julián Álvarez,ar ARG,FW,Atlético Madrid,es La Liga,25-353,2000.0,20,19,1433,...,0.30,0.72,0.26,0.56,3,3.930764,False,0.660241,True,25.0
27,Takefusa Kubo,jp JPN,"MF,FW",Real Sociedad,es La Liga,24-229,2001.0,18,13,1179,...,0.24,0.43,0.19,0.43,3,3.943149,False,0.661655,True,26.0
35,Michael Olise,fr FRA,FW,Bayern Munich,de Bundesliga,24-038,2001.0,18,14,1370,...,0.66,1.17,0.51,1.17,3,3.957919,False,0.667279,True,27.0
4,Ander Barrenetxea,es ESP,"MF,FW",Real Sociedad,es La Liga,24-023,2001.0,18,12,1052,...,0.35,0.51,0.17,0.51,3,3.979100,False,0.670412,True,28.0
29,Khvicha Kvaratskhelia,ge GEO,FW,Paris Saint-Germain,fr Ligue 1,24-341,2001.0,15,9,749,...,0.30,0.59,0.29,0.59,3,3.992848,False,0.670716,True,29.0
7,Rayan Cherki,fr FRA,"MF,FW",Manchester City,eng Premier League,22-155,2003.0,17,10,885,...,0.61,0.79,0.18,0.79,3,4.010533,False,0.677317,True,30.0
11,Romain Del Castillo,fr FRA,"FW,MF",Brest,fr Ligue 1,29-296,1996.0,17,17,1369,...,0.32,0.73,0.04,0.36,3,4.002292,False,0.679528,True,31.0
53,Carlos Vicente,es ESP,"MF,FW",Alavés,es La Liga,26-271,1999.0,20,10,1176,...,0.27,0.54,0.08,0.35,3,4.157824,False,0.720924,True,32.0
46,Giuliano Simeone,ar ARG,"MF,FW",Atlético Madrid,es La Liga,23-032,2002.0,19,16,1421,...,0.23,0.44,0.21,0.44,3,4.158569,False,0.723077,True,33.0
23,Callum Hudson-Odoi,eng ENG,FW,Nottingham Forest,eng Premier League,25-073,2000.0,20,12,1210,...,0.18,0.32,0.15,0.32,3,4.169409,False,0.724417,True,34.0
52,Leandro Trossard,be BEL,FW,Arsenal,eng Premier League,31-046,1994.0,18,12,1176,...,0.18,0.49,0.32,0.49,3,4.171776,False,0.724778,True,35.0
8,Félix Correia,pt POR,"FW,MF",Lille,fr Ligue 1,24-362,2001.0,18,13,1071,...,0.29,0.49,0.20,0.49,3,4.197717,False,0.730981,True,36.0
14,Abde Ezzalzouli,ma MAR,FW,Real Betis,es La Liga,24-033,2001.0,11,9,780,...,0.34,0.75,0.41,0.75,3,4.253319,False,0.743078,True,37.0
38,Matteo Politano,it ITA,"MF,FW",Napoli,it Serie A,32-169,1993.0,21,15,1311,...,0.20,0.30,0.11,0.30,3,4.234238,False,0.743148,True,38.0
5,Álex Berenguer,es ESP,"FW,MF",Athletic Club,es La Liga,30-199,1995.0,18,16,1286,...,0.26,0.46,0.20,0.46,3,4.240137,False,0.744579,True,39.0
33,Jacob Murphy,eng ENG,FW,Newcastle United,eng Premier League,30-329,1995.0,18,12,1010,...,0.31,0.56,0.25,0.56,3,4.253886,False,0.745892,True,40.0
48,Matìas Soulé,ar ARG,"MF,FW",Roma,it Serie A,22-279,2003.0,21,18,1385,...,0.14,0.33,0.19,0.33,3,4.256026,False,0.749731,True,41.0
0,Maghnes Akliouche,fr FRA,"MF,FW",Monaco,fr Ligue 1,23-328,2002.0,17,16,1385,...,0.18,0.44,0.25,0.44,3,4.317693,False,0.766764,True,42.0
32,Diego Moreira,be BEL,"DF,FW",Strasbourg,fr Ligue 1,21-166,2004.0,17,15,1307,...,0.30,0.36,0.06,0.36,3,4.333442,False,0.770518,True,43.0
6,Jarrod Bowen,eng ENG,"FW,MF",West Ham United,eng Premier League,29-030,1996.0,22,22,1980,...,0.09,0.32,0.23,0.32,3,4.322008,False,0.771633,True,44.0
24,João Pedro,br BRA,"FW,MF",Chelsea,eng Premier League,24-115,2001.0,22,19,1598,...,0.17,0.55,0.38,0.55,3,4.337429,False,0.773687,True,45.0
51,Bazoumana Touré,ci CIV,"FW,MF",Hoffenheim,de Bundesliga,19-323,2006.0,15,14,1110,...,0.20,0.37,0.17,0.37,3,4.362155,False,0.776768,True,46.0
9,Cucho,co COL,FW,Real Betis,es La Liga,26-274,1999.0,19,19,1645,...,0.21,0.63,0.38,0.59,3,4.359687,False,0.780133,True,47.0
41,Morgan Rogers,eng ENG,"FW,MF",Aston Villa,eng Premier League,23-177,2002.0,22,22,1957,...,0.16,0.32,0.16,0.32,3,4.370136,False,0.784807,True,48.0
49,Issa Soumaré,sn SEN,"FW,MF",Le Havre,fr Ligue 1,25-101,2000.0,18,18,1553,...,0.14,0.67,0.38,0.53,3,4.401575,False,0.791111,True,49.0
18,Yann Gboho,fr FRA,"MF,FW",Toulouse,fr Ligue 1,25-005,2001.0,17,16,1440,...,0.13,0.34,0.20,0.34,3,4.410706,False,0.792856,True,50.0
50,Marcus Tavernier,eng ENG,"MF,FW",Bournemouth,eng Premier League,26-303,1999.0,21,19,1691,...,0.13,0.35,0.18,0.31,3,4.432059,False,0.800407,True,51.0
36,Mikel Oyarzabal,es ESP,FW,Real Sociedad,es La Liga,28-273,1997.0,17,17,1497,...,0.24,0.69,0.31,0.54,3,4.502938,False,0.818731,True,52.0
47,Moses Simon,ng NGA,"FW,MF",Paris FC,fr Ligue 1,30-191,1995.0,16,14,1146,...,0.16,0.34,0.18,0.34,3,4.542499,False,0.826909,True,53.0
28,Mohammed Kudus,gh GHA,"FW,MF",Tottenham Hotspur,eng Premier League,25-170,2000.0,19,19,1535,...,0.17,0.28,0.11,0.28,3,4.543467,False,0.830183,True,54.0
55,Florian Wirtz,de GER,"MF,FW",Liverpool,eng Premier League,22-261,2003.0,21,17,1495,...,0.15,0.41,0.26,0.41,3,4.600157,False,0.845570,True,55.0
30,Kylian Mbappé,fr FRA,FW,Real Madrid,es La Liga,27-030,1998.0,19,19,1660,...,0.31,1.22,0.63,0.95,3,4.784676,False,0.897613,True,56.0
19,Morgan Gibbs-White,eng ENG,"MF,FW",Nottingham Forest,eng Premier League,25-357,2000.0,22,21,1871,...,0.06,0.36,0.26,0.32,3,5.148795,False,0.999417,True,57.0
56,Lamine Yamal,es ESP,FW,Barcelona,es La Liga,18-190,2007.0,16,15,1349,...,0.39,0.75,0.25,0.64,3,0.000000,True,NaN,False,NaN

In [46]:
df_final.to_excel(
    "/home/fjordan/Documentos/Proyectos/Personales/proyectos-Python/Analisis Lamine-Pedri/data/clean/df_lamine_tableau.xlsx",
    index=False
)

In [47]:
df_top10 = df_replacements[
    ["Player", "Squad","Playing Time_Min", "distance_to_lamine", "replacement_score"]
].head(10)

In [48]:
df_top10 = df_top10.reset_index(drop=True)
df_top10["Rank"] = df_top10.index + 1

In [49]:
df_top10 = df_top10[[
    "Rank",
    "Player",
    "Squad",
    "Playing Time_Min",
    "distance_to_lamine",
    "replacement_score"
]]

In [50]:
df_top10.to_excel(
    "/home/fjordan/Documentos/Proyectos/Personales/proyectos-Python/Analisis Lamine-Pedri/data/clean/df_top10.xlsx",
    index=False
)

In [51]:
df_top10

,Rank,Player,Squad,Playing Time_Min,distance_to_lamine,replacement_score
0,1,Kenan Yıldız,Juventus,1661,1.564561,0.008192
1,2,Jeremy Doku,Manchester City,1168,2.457045,0.251082
2,3,Charles De Ketelaere,Atalanta,1409,2.690434,0.317476
3,4,Nico Williams,Athletic Club,1128,2.792286,0.343321
4,5,Bukayo Saka,Arsenal,1456,2.888168,0.372430
5,6,Pedro Neto,Chelsea,1729,2.911810,0.380728
6,7,Cody Gakpo,Liverpool,1422,2.919990,0.380976
7,8,Antony,Real Betis,1261,2.934520,0.383753
8,9,Jack Grealish,Everton,1627,3.100912,0.432334
9,10,Mason Greenwood,Marseille,1355,3.125817,0.437331